# Build Image 
FROM golang:1.18.2-alpine3.16  AS builder 
WORKDIR /app
COPY . . 
RUN go build -o main main.go

#RUN stage 
FROM alpine:3.13
WORKDIR /app 
COPY --from=builder /app/main . 

EXPOSE 8080 
CMD ["/app/main"]